name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: staging
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Generate build number
      run: echo "The build number $GITHUB_RUN_NUMBER 🏗"
    - name: Install dependencies
      run: |
           npm install
           npm install -g yarn
           npm install -g expo-cli
    - name: Create .env
      run: |
        touch .env &&
        echo "NODE_ENV=${NODE_ENV}" > .env &&
        echo "SERVERLESS_DELILUNCHER_API_BASE_URL=${SERVERLESS_DELILUNCHER_API_BASE_URL}" >> .env
      env:
        NODE_ENV: ${{ secrets.NODE_ENV }}
        SERVERLESS_DELILUNCHER_API_BASE_URL: ${{ secrets.SERVERLESS_DELILUNCHER_API_BASE_URL }}
    - name: Build docker 🐳
      run: docker build . -t=deliluncher-app:ghb-$GITHUB_RUN_NUMBER